### ISSUE TITLE
1. vertaisarviointi

### ISSUE THREAD

**Issue by xcvbnmas** [Robomarti/Tietokantasovellus#1]
Kirjautuminen ja perustoiminnot toimivat hyvin, ja sovellusta on helppo ja mukava käyttää. Sovelluksen lähdekoodi on selkeää. 
Muutama huomio/parannusehdotus:
- Virheilmoitukset käyttäjätunnusta luodessa vaikuttavat toimivan muuten hyvin, mutta tilanteessa, jossa yrittää luoda käyttäjätunnusta antamatta salasanaa, virheilmoitusta ei tule ollenkaan. Toisin sanoen tällä hetkellä on mahdollista luoda käyttäjätunnus ilman salasanaa. 
- Käyttäjän luomat yksityiset reseptit eivät tällä hetkellä taida näkyä käyttäjälle itselleen muuten kuin hakemalla. Sovelluksen käyttämistä voisi helpottaa, jos käyttäjä löytäisi omat yksityiset reseptinsä jostain kootusti.

**Comment by Robomarti** [comment]
Kiitos ehdotuksista, en ollutkaan huomannut että käyttäjän voi luoda täyttämättä käyttäjänimi- ja salasanakenttiä. Lisäsin molemmat toiminnot sovellukseeni.
